# NeON Build File (http://github.com/c4s4/neon)

extends: golang
default: [fmt, check, test]
expose:  [fmt, check, test, release]
# configuration: '~/.neon/github.yml'
# GITHUB_TOKEN: 'abcdefghijklmnopqrstuvwxyz0123456789'

targets:

  build:
    depends: version
    steps:
    - super:
    - for: name
      in: [desc, help, targets]
      do:
      - move:   ={BUILD_DIR}/={name}
        tofile: ={BUILD_DIR}/make-={name}

  binaries:
    depends: version
    steps:
    - super:
    - for: file
      in:  find(BUILD_DIR+"/bin", "*")
      do:
      - move:   ={BUILD_DIR}/bin/={file}
        tofile: ={BUILD_DIR}/bin/make-={file}
